# Generated by Django 4.1.7 on 2023-06-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cart_id', models.IntegerField()),
                ('shipment_id', models.IntegerField()),
                ('payment_id', models.IntegerField()),
            ],
        ),
    ]
