# Generated by Django 4.1.7 on 2023-06-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipment_id',
        ),
    ]
