# Generated by Django 4.1.7 on 2023-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
