# Generated by Django 4.1.7 on 2023-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='size_name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='info',
            field=models.JSONField(default=None, null=True),
        ),
    ]
