# Generated by Django 4.1.7 on 2023-06-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_model', '0004_clothinventory_remove_cloth_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothinventory',
            name='cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='clothes_model.cloth'),
        ),
    ]
