# Generated by Django 4.1.7 on 2023-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(default='Chưa thành toán', max_length=20)),
                ('payment_type', models.CharField(default='Bằng tiền mặt', max_length=20)),
                ('credits_card_number', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
    ]
