# Generated by Django 4.1.7 on 2023-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.IntegerField(default=None),
        ),
    ]
