# Generated by Django 4.1.7 on 2023-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('category', models.CharField(default='Book', max_length=50, null=True)),
                ('size', models.CharField(default=None, max_length=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
